spring:
  application:
    name: service-social              # Matches the config file name in the repo (e.g., service-user.yml)

  kafka:
    #    bootstrap-servers: kafka:9092

#    consumer:
#      bootstrap-servers: kafka:9092
#      group-id: my-consumer-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      max-poll-records: 500
    producer:
      bootstrap-servers: localhost:9092
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer