spring:
  application:
    name: service-social         # Unique name for Eureka registration
  datasource:
    url: jdbc:mysql://localhost:3306/aspiro-social?useSSL=false&serverTimezone=UTC
    username: root
    password: talel
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Options: validate | update | create | create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
server:
  port: 8301

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka server URL
  instance:
    preferIpAddress: true