spring:
  application:
    name: service-goal         # Unique name for Eureka registration
#  datasource:
#    url: jdbc:mysql://localhost:3306/service_a_db  # Replace with actual DB details
#    username: your_db_username
#    password: your_db_password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

server:
  port: 8501

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka server URL
  instance:
    preferIpAddress: true