spring:
  application:
    name: service-notification              # Matches the config file name in the repo (e.g., service-user.yml)

  kafka:
#    bootstrap-servers: kafka:9092

    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: true
#    producer:
#      bootstrap-servers: kafka:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      acks: all
#      retries: 3
#      batch-size: 16384
#      buffer-memory: 33554432
