server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/   # Eureka server URL
  instance:
    preferIpAddress: true


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///config-repo/
      label: main

logging:
  level:
    root: INFO
    org.springframework.cloud.config.server: DEBUG
    org.springframework.boot.context.config: DEBUG