spring:
  application:
    name: service-user         # Unique name for Eureka registration
  cloud:
    config:
      overrideNone: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/service_a_db  # Replace with actual DB details
#    username: your_db_username
#    password: your_db_password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/   # Eureka server URL
  instance:
    preferIpAddress: true
    #    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
